import { addDoc, collection, doc, getDoc, getDocs, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore'
import { db } from '../firebase/firebase'

const COLLECTION = 'enquiries'
const mapDocument = (snapshot) => ({ id: snapshot.id, ...snapshot.data() })
const clean = (data) => ({
  enquiryDate: data.enquiryDate,
  companyName: (data.companyName || '').trim(),
  contactNumber: (data.contactNumber || '').trim(),
  leadGeneratedBy: data.leadGeneratedBy,
  priority: data.priority,
  nextFollowUp: data.priority === 'COLD' ? '' : data.nextFollowUp || '',
  remarks: (data.remarks || '').trim(),
  customerId: data.customerId || '', customerName: data.customerName || '',
  receivedExecutiveId: data.receivedExecutiveId || '', receivedExecutiveName: data.receivedExecutiveName || '',
  productId: data.productId || '', productName: data.productName || '',
  callDisposition: data.callDisposition || '',
  assignedExecutiveId: data.assignedExecutiveId || '', assignedExecutiveName: data.assignedExecutiveName || '',
  followUpLeadId: data.followUpLeadId, followUpLeadName: data.followUpLeadName,
})

const validate = (data) => {
  if (!(data.companyName || '').trim()) throw new Error('Company Name is required.')
  if (!/^\d{10}$/.test((data.contactNumber || '').trim())) throw new Error('Enter a valid 10-digit Contact Number.')
  if (!data.leadGeneratedBy) throw new Error('Lead Generated By is required.')
  if (!data.priority) throw new Error('Priority is required.')
  if (data.priority !== 'COLD' && !data.nextFollowUp) throw new Error('Next Follow Up is required for HOT and WARM enquiries.')
  if (!data.followUpLeadId || !data.followUpLeadName) throw new Error('Logged-in Follow Up Lead is required.')
}

export const getEnquiries = async () => {
  const snapshot = await getDocs(query(collection(db, COLLECTION), orderBy('createdAt', 'desc')))
  return snapshot.docs.map(mapDocument)
}
export const getEnquiryById = async (id) => {
  const snapshot = await getDoc(doc(db, COLLECTION, id))
  return snapshot.exists() ? mapDocument(snapshot) : null
}
export const createEnquiry = async (data) => {
  validate(data)
  const ref = await addDoc(collection(db, COLLECTION), { ...clean(data), createdAt: serverTimestamp(), updatedAt: serverTimestamp() })
  return mapDocument(await getDoc(ref))
}
export const updateEnquiry = async (id, data) => {
  validate(data)
  const ref = doc(db, COLLECTION, id)
  await updateDoc(ref, { ...clean(data), updatedAt: serverTimestamp() })
  return mapDocument(await getDoc(ref))
}
export const enquiryService = { getEnquiries, getEnquiryById, createEnquiry, updateEnquiry }
