import { addDoc, collection, doc, getDoc, getDocs, orderBy, query, serverTimestamp, updateDoc } from 'firebase/firestore'
import { db } from '../firebase/firebase'

const COLLECTION = 'enquiries'
const mapDocument = (snapshot) => {
  const data = snapshot.data()
  return { id: snapshot.id, ...data, leadCreationDate: data.leadCreationDate || data.enquiryDate || '', contactName: data.contactName ?? data.companyName ?? '' }
}
const clean = (data) => ({
  leadCreationDate: data.leadCreationDate || data.enquiryDate,
  enquiryDate: data.leadCreationDate || data.enquiryDate,
  contactName: (data.contactName || data.companyName || '').trim(),
  companyName: (data.contactName || data.companyName || '').trim(),
  contactNumber: (data.contactNumber || '').trim(),
  leadGeneratedBy: data.leadGeneratedBy,
  priority: data.priority,
  nextFollowUp: ['HOT', 'WARM'].includes(data.priority) && data.callDisposition === 'FOLLOWUP' ? data.nextFollowUp || '' : '',
  closedOn: data.callDisposition === 'COMPLETED' ? data.closedOn || '' : '',
  remarks: (data.remarks || '').trim(),
  customerId: data.customerId || '', customerName: data.customerName || '',
  areaId: data.areaId || '', areaName: data.areaName || '',
  receivedExecutiveId: data.receivedExecutiveId || '', receivedExecutiveName: data.receivedExecutiveName || '',
  productId: data.productId || '', productName: data.productName || '',
  callDisposition: data.callDisposition || '',
  assignedExecutiveId: data.assignedExecutiveId || '', assignedExecutiveName: data.assignedExecutiveName || '',
  followUpLeadId: data.assignedExecutiveId || data.followUpLeadId, followUpLeadName: data.assignedExecutiveName || data.followUpLeadName,
})

const validate = (data) => {
  if (!(data.leadCreationDate || data.enquiryDate)) throw new Error('Lead Creation Date is required.')
  if (!/^\d{10}$/.test((data.contactNumber || '').trim())) throw new Error('Enter a valid 10-digit Contact Number.')
  if (!data.leadGeneratedBy) throw new Error('Lead Generated By is required.')
  if (!data.priority) throw new Error('Priority is required.')
  const allowed = data.priority === 'COLD' ? ['NOT INTERESTED', 'DROPPED'] : ['FOLLOWUP', 'COMPLETED']
  if (!data.callDisposition || !allowed.includes(data.callDisposition)) throw new Error('Select a valid Call Disposition for the selected Priority.')
  if (['HOT', 'WARM'].includes(data.priority) && data.callDisposition === 'FOLLOWUP' && !data.nextFollowUp) throw new Error('Next Follow Up is required.')
  if (data.callDisposition === 'COMPLETED' && !data.closedOn) throw new Error('Closed On date is required.')
  if (!data.followUpLeadId || !data.followUpLeadName) throw new Error('Logged-in Follow Up Lead is required.')
}

export const getEnquiries = async () => {
  const snapshot = await getDocs(query(collection(db, COLLECTION), orderBy('createdAt', 'desc')))
  return snapshot.docs.map(mapDocument)
}
export const getEnquiryById = async (id) => {
  const snapshot = await getDoc(doc(db, COLLECTION, id))
  return snapshot.exists() ? mapDocument(snapshot) : null
}
export const createEnquiry = async (data) => {
  validate(data)
  const ref = await addDoc(collection(db, COLLECTION), { ...clean(data), createdAt: serverTimestamp(), updatedAt: serverTimestamp() })
  return mapDocument(await getDoc(ref))
}
export const updateEnquiry = async (id, data) => {
  validate(data)
  const ref = doc(db, COLLECTION, id)
  await updateDoc(ref, { ...clean(data), updatedAt: serverTimestamp() })
  return mapDocument(await getDoc(ref))
}
export const enquiryService = { getEnquiries, getEnquiryById, createEnquiry, updateEnquiry }
