import { useEffect, useMemo, useState } from 'react'
import { Download, Pencil, Search } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageHeader from '../../components/common/PageHeader'
import Button from '../../components/common/Button'
import CommonPagination from '../../components/common/CommonPagination'
import { freeSupportVoucherService } from '../../services/freeSupportVoucherService'
import { exportToCsv } from '../../utils/exportCsv'
import { formatReportCurrency, formatReportDate } from '../../utils/reportUtils'
import { getCurrentMonthDateRange } from '../../utils/reportDateRange'
import { useAuth } from '../../context/AuthContext'

const FreeSupportRegisterReport = () => {
  const { hasPermission } = useAuth(); const canEdit = hasPermission('salesVouchers', 'edit'); const navigate = useNavigate(); const defaults = getCurrentMonthDateRange()
  const [vouchers, setVouchers] = useState([]); const [fromDate, setFromDate] = useState(defaults.fromDate); const [toDate, setToDate] = useState(defaults.toDate); const [range, setRange] = useState(null); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState('')
  useEffect(() => { freeSupportVoucherService.getFreeSupportVouchers().then(setVouchers).catch(() => setError('Unable to load Free Support Register.')) }, [])
  const rows = useMemo(() => !range ? [] : vouchers.filter((voucher) => voucher.voucherDate >= range.from && voucher.voucherDate <= range.to && (!search || [voucher.voucherNumber, voucher.customerName, voucher.executiveName, voucher.items?.[0]?.itemName].some((value) => String(value || '').toLowerCase().includes(search.toLowerCase())))), [vouchers, range, search])
  const pageSize = 10; const pages = Math.max(1, Math.ceil(rows.length / pageSize)); const paged = rows.slice((page - 1) * pageSize, page * pageSize)
  const download = () => exportToCsv({ filename: `free-support-register-${range.from}-to-${range.to}.csv`, headers: ['Voucher No', 'Date', 'Customer', 'Executive', 'Category', 'Free Support', 'Product', 'Serial No', 'Duration', 'From', 'To', 'Amount', 'Status'], rows: rows.map((voucher) => { const item = voucher.items?.[0] || {}; return [voucher.voucherNumber, formatReportDate(voucher.voucherDate), voucher.customerName, voucher.executiveName, voucher.category, voucher.freeSupport, item.itemName, item.serialNo, item.duration, formatReportDate(item.amcFromDate), formatReportDate(item.amcToDate), item.amount, voucher.status] }) })
  return <div className="page-stack"><PageHeader title="Free Support Register Report" subtitle="View Free Support vouchers by selected date range." />{error && <div className="auth-error">{error}</div>}<section className="panel-card report-section"><div className="report-filter-grid"><label className="field"><span>From Date *</span><input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label className="field"><span>To Date *</span><input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label></div><div className="form-actions report-actions"><Button type="button" onClick={() => { if (fromDate && toDate >= fromDate) { setRange({ from: fromDate, to: toDate }); setPage(1) } }}>Generate Report</Button><Button type="button" variant="secondary" onClick={() => { setRange(null); setSearch('') }}>Clear</Button><Button type="button" variant="ghost" onClick={download} disabled={!rows.length}><Download size={15} /> Download Report</Button></div>{range && <><div className="toolbar report-toolbar"><div className="search-box"><Search size={16} /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} placeholder="Search voucher, customer, executive or product..." /></div></div><div className="table-wrap report-table"><table><thead><tr><th>S.No</th><th>Voucher No</th><th>Date</th><th>Customer</th><th>Executive</th><th>Free Support</th><th>Product</th><th>Duration</th><th>From</th><th>To</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{!paged.length && <tr><td colSpan="13" className="text-center">No Free Support vouchers found.</td></tr>}{paged.map((voucher, index) => { const item = voucher.items?.[0] || {}; return <tr key={voucher.id}><td>{(page - 1) * pageSize + index + 1}</td><td>#{voucher.voucherNumber}</td><td>{formatReportDate(voucher.voucherDate)}</td><td>{voucher.customerName}</td><td>{voucher.executiveName}</td><td>{voucher.freeSupport}</td><td>{item.itemName}</td><td>{item.duration}</td><td>{formatReportDate(item.amcFromDate)}</td><td>{formatReportDate(item.amcToDate)}</td><td>{formatReportCurrency(item.amount)}</td><td>{voucher.status}</td><td>{canEdit && <button className="executive-action-btn" onClick={() => navigate('/free-support-voucher')}><Pencil size={13} /> Edit</button>}</td></tr> })}</tbody></table></div><CommonPagination currentPage={page} totalPages={pages} totalRecords={rows.length} onPrevious={() => setPage((value) => Math.max(1, value - 1))} onNext={() => setPage((value) => Math.min(pages, value + 1))} /></>}</section></div>
}
export default FreeSupportRegisterReport
