import { useEffect, useMemo, useState } from 'react'
import { Pencil, Trash2 } from 'lucide-react'
import { useDispatch, useSelector } from 'react-redux'
import { useLocation } from 'react-router-dom'
import PageHeader from '../../components/common/PageHeader'
import Button from '../../components/common/Button'
import { useAuth } from '../../context/AuthContext'
import { fetchCustomers, selectActiveCustomers } from '../../features/customers/customerSlice'
import { fetchExecutives, selectActiveExecutives } from '../../features/executives/executiveSlice'
import { fetchProducts, selectActiveProducts } from '../../features/products/productSlice'
import { freeSupportVoucherService } from '../../services/freeSupportVoucherService'
import { formatDate } from '../../utils/dateUtils'

const dateValue = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const emptyForm = () => ({ voucherDate: dateValue(), customerId: '', customerName: '', executiveId: '', executiveName: '', category: '', narration: '', freeSupport: '', serialNo: '', productId: '', itemName: '', duration: '', unit: '', amcFromDate: '', amcToDate: '', amount: '' })
const durationMonths = { '1 Month': 1, '2 Months': 2, '3 Months': 3, '4 Months': 4, '5 Months': 5, '6 Months': 6, '10 Months': 10, '1 Year': 12 }
const calculateTo = (from, duration) => { if (!from || !durationMonths[duration]) return ''; const [year, month, day] = from.split('-').map(Number); const index = month - 1 + durationMonths[duration]; const targetYear = year + Math.floor(index / 12); const targetMonth = index % 12; const result = new Date(targetYear, targetMonth, Math.min(day, new Date(targetYear, targetMonth + 1, 0).getDate())); result.setDate(result.getDate() - 1); return dateValue(result) }

const FreeSupportVoucher = () => {
  const { hasPermission } = useAuth(); const canAdd = hasPermission('salesVouchers', 'add'); const canEdit = hasPermission('salesVouchers', 'edit'); const canDelete = hasPermission('salesVouchers', 'delete')
  const dispatch = useDispatch(); const location = useLocation(); const renewalVoucher = location.state?.renewVoucher || null; const renewalItem = renewalVoucher?.items?.[0] || {}
  const customers = useSelector(selectActiveCustomers); const executives = useSelector(selectActiveExecutives); const products = useSelector(selectActiveProducts)
  const [form, setForm] = useState(() => renewalVoucher ? { ...emptyForm(), customerId: renewalVoucher.customerId || '', customerName: renewalVoucher.customerName || '', executiveId: renewalVoucher.executiveId || '', executiveName: renewalVoucher.executiveName || '', category: 'Renewal', freeSupport: 'Yes', serialNo: renewalItem.serialNo || '', productId: renewalItem.productId || '', itemName: renewalItem.itemName || '', duration: renewalItem.duration || '', unit: renewalItem.unit || '', amount: String(renewalItem.amount || '') } : emptyForm()); const [voucherNumber, setVoucherNumber] = useState(''); const [vouchers, setVouchers] = useState([]); const [editingId, setEditingId] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  const load = async (date = form.voucherDate) => { const [records, next] = await Promise.all([freeSupportVoucherService.getFreeSupportVouchers(), freeSupportVoucherService.getNextFreeSupportVoucherNumber(date)]); setVouchers(records); if (!editingId) setVoucherNumber(next) }
  useEffect(() => {
    let active = true
    dispatch(fetchCustomers()); dispatch(fetchExecutives()); dispatch(fetchProducts())
    Promise.all([freeSupportVoucherService.getFreeSupportVouchers(), freeSupportVoucherService.getNextFreeSupportVoucherNumber(dateValue())])
      .then(([records, next]) => { if (active) { setVouchers(records); setVoucherNumber(next) } })
      .catch(() => { if (active) setError('Unable to load Free Support vouchers.') })
    return () => { active = false }
  }, [dispatch])
  const setField = (field, value) => setForm((current) => { const next = { ...current, [field]: value }; if (field === 'duration' || field === 'amcFromDate') next.amcToDate = calculateTo(next.amcFromDate, next.duration); return next })
  const save = async () => { setError(''); if (!form.customerId) return setError('Select a valid Party.'); if (!form.executiveId) return setError('Select a valid Executive.'); if (!form.category) return setError('Category is required.'); if (!form.freeSupport) return setError('Free Support option is required.'); if (!form.productId) return setError('Select a valid Item.'); if (!form.duration) return setError('Duration is required.'); if (!form.amcFromDate || !form.amcToDate) return setError('Free Support From and To dates are required.'); if (Number(form.amount) <= 0) return setError('Amount must be greater than 0.'); setSaving(true); try { const payload = { ...form, renewalSourceVoucherId: renewalVoucher?.id || '', renewalSourceVoucherNumber: renewalVoucher?.voucherNumber || '', items: [{ serialNo: form.serialNo, productId: form.productId, itemName: form.itemName, duration: form.duration, unit: form.unit, amcFromDate: form.amcFromDate, amcToDate: form.amcToDate, amount: form.amount }], totalAmount: form.amount }; const saved = editingId ? await freeSupportVoucherService.updateFreeSupportVoucher(editingId, payload) : await freeSupportVoucherService.createFreeSupportVoucher(payload); setMessage(`Free Support voucher ${saved.voucherNumber} saved successfully.`); setEditingId(''); setForm(emptyForm()); await load(dateValue()) } catch (reason) { setError(reason.message || 'Unable to save Free Support voucher.') } finally { setSaving(false) } }
  const edit = (voucher) => { const item = voucher.items?.[0] || {}; setEditingId(voucher.id); setVoucherNumber(voucher.voucherNumber); setForm({ ...emptyForm(), ...voucher, ...item, amount: String(item.amount || '') }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const remove = async (voucher) => { if (!window.confirm(`Delete Free Support voucher #${voucher.voucherNumber}?`)) return; await freeSupportVoucherService.deleteFreeSupportVoucher(voucher.id); await load() }
  const productOptions = useMemo(() => products, [products])
  return <div className="page-stack"><PageHeader title="Free Support" subtitle="Create and manage Free Support vouchers." /><section className="panel-card form-card"><div className="form-grid two-col" style={{ gap: 18 }}>
    <label className="field"><span>Voucher Number</span><input value={voucherNumber} readOnly disabled /></label><label className="field"><span>Date *</span><input type="date" value={form.voucherDate} onChange={async (event) => { setField('voucherDate', event.target.value); if (!editingId) setVoucherNumber(await freeSupportVoucherService.getNextFreeSupportVoucherNumber(event.target.value)) }} /></label>
    <label className="field"><span>Party Name *</span><select value={form.customerId} onChange={(event) => { const item = customers.find((value) => value.id === event.target.value); setForm((current) => ({ ...current, customerId: item?.id || '', customerName: item?.customerName || '' })) }}><option value="">Select customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.customerName}</option>)}</select></label>
    <label className="field"><span>Executive *</span><select value={form.executiveId} onChange={(event) => { const item = executives.find((value) => value.id === event.target.value); setForm((current) => ({ ...current, executiveId: item?.id || '', executiveName: item?.name || '' })) }}><option value="">Select executive</option>{executives.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="field"><span>Category *</span><select value={form.category} onChange={(event) => setField('category', event.target.value)}><option value="">Select category</option><option>New</option><option>Renewal</option></select></label><label className="field"><span>Free Support *</span><select value={form.freeSupport} onChange={(event) => setField('freeSupport', event.target.value)}><option value="">Select option</option><option>Yes</option><option>No</option></select></label>
  </div><label className="field"><span>Narration</span><textarea value={form.narration} onChange={(event) => setField('narration', event.target.value)} /></label><div className="panel-heading voucher-products-heading"><h2>Item Details</h2></div><div className="form-grid voucher-item-grid">
    <label className="field"><span>Serial No</span><input value={form.serialNo} onChange={(event) => setField('serialNo', event.target.value)} /></label><label className="field"><span>Item *</span><select value={form.productId} onChange={(event) => { const item = productOptions.find((value) => value.id === event.target.value); setForm((current) => ({ ...current, productId: item?.id || '', itemName: item?.itemName || '', unit: item?.unit || '' })) }}><option value="">Select item</option>{productOptions.map((item) => <option key={item.id} value={item.id}>{item.itemName}</option>)}</select></label>
    <label className="field"><span>Duration *</span><select value={form.duration} onChange={(event) => setField('duration', event.target.value)}><option value="">Select duration</option>{Object.keys(durationMonths).map((value) => <option key={value}>{value}</option>)}</select></label><label className="field"><span>Unit</span><input value={form.unit} readOnly /></label><label className="field"><span>Amount *</span><input type="number" min="0.01" value={form.amount} onChange={(event) => setField('amount', event.target.value)} /></label><label className="field"><span>Free Support From *</span><input type="date" value={form.amcFromDate} onChange={(event) => setField('amcFromDate', event.target.value)} /></label><label className="field"><span>Free Support To *</span><input type="date" value={form.amcToDate} onChange={(event) => setField('amcToDate', event.target.value)} /></label>
  </div>{error && <div className="auth-error">{error}</div>}{message && <div className="auth-success">{message}</div>}<div className="form-actions">{(editingId ? canEdit : canAdd) && <Button onClick={save} disabled={saving}>{saving ? 'Saving...' : editingId ? 'Update Voucher' : 'Save Voucher'}</Button>}<Button variant="secondary" onClick={() => { setEditingId(''); setForm(emptyForm()); load(dateValue()) }}>Clear</Button></div></section>
  <section className="panel-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Recent Free Support Vouchers</h2></div><div className="table-wrap"><table><thead><tr><th>S.No</th><th>Voucher No</th><th>Date</th><th>Party</th><th>Executive</th><th>Free Support</th><th>Duration</th><th>Actions</th></tr></thead><tbody>{!vouchers.length && <tr><td colSpan="8" className="text-center">No vouchers found.</td></tr>}{vouchers.map((voucher, index) => <tr key={voucher.id}><td>{index + 1}</td><td>#{voucher.voucherNumber}</td><td>{formatDate(voucher.voucherDate)}</td><td>{voucher.customerName}</td><td>{voucher.executiveName}</td><td>{voucher.freeSupport}</td><td>{voucher.items?.[0]?.duration || '—'}</td><td><div className="table-actions">{canEdit && <button className="executive-action-btn" onClick={() => edit(voucher)}><Pencil size={13} /> Edit</button>}{canDelete && <button className="executive-action-btn delete" onClick={() => remove(voucher)}><Trash2 size={13} /> Delete</button>}</div></td></tr>)}</tbody></table></div></section></div>
}
export default FreeSupportVoucher
